version: "3.3"
services:
  web-server:
    image: web-server-task:latest
    container_name: web-server
    ports:
      - "9000:8080"
    depends_on:
      - mongo-seed

  mongo-seed:
    image: mongo
    container_name: mongo-seed
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-seed/initdb.js:/docker-entrypoint-initdb.d/initdb.js
      - ./build/db/:/data/db